Feature/tweet
shinonome-inc/backend-final-assignment-EndoKenta pull request #3
Opened 2022-09-05 05:06 UTC by pg-endokenta

2022-09-06 01:37 UTC, okapiinosuke reviewed
基本的に綺麗に書けていて良いと思います！
少しコメントしました。

2022-09-06 01:37 UTC, okapiinosuke commented on templates/tweets/detail.html
> +<a href="{% url 'tweets:delete' object.pk %}">ツイート削除はこちら</a>
作成者がアクセスした時だけ見れるようにした方がいいですね。

2022-09-06 01:37 UTC, okapiinosuke commented on templates/base.html
>      <a href="{% url 'accounts:logout' %}">ロウグアウトはこちら</a>
ログアウト

2022-09-06 01:37 UTC, okapiinosuke commented on accounts/models.py
> +    slug = models.SlugField(max_length=150, blank=False, unique=True)
これはusernameと同じなため不要です。pkを用いてアクセスしましょう。

2022-09-06 01:37 UTC, okapiinosuke commented on accounts/urls.py
> +    ),
`<slug:slug>`
を
`<int:pk>`
にしてアクセスできるようにしましょう。

2022-09-06 07:56 UTC, pg-endokenta commented on templates/tweets/detail.html
> +<a href="{% url 'tweets:delete' object.pk %}">ツイート削除はこちら</a>
ツイート削除のリンクをツイートの作成者のみに表示させるようにしました

2022-09-06 07:57 UTC, pg-endokenta commented on templates/base.html
>      <a href="{% url 'accounts:logout' %}">ロウグアウトはこちら</a>
こちらはどのような意図があるのでしょうか？

2022-09-06 08:07 UTC, pg-endokenta commented on accounts/urls.py
> +    ),
バックエンドの最終課題テスト項目要件整理の画面と機能（v2）によるとUserProfileViewのエンドポイントがpkではなくusernameになっているためslugを用いました。
ここはこのままでも良いと思います。
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917

2022-09-06 09:06 UTC, okapiinosuke commented on accounts/urls.py
> +    ),
なるほど、見落としていました。すみません。
そのままで大丈夫です！

2022-09-06 09:07 UTC, okapiinosuke commented on templates/base.html
>      <a href="{% url 'accounts:logout' %}">ロウグアウトはこちら</a>
タイプミスですね。
ロウグアウトになっています。

2022-09-06 09:58 UTC, pg-endokenta commented on templates/base.html
>      <a href="{% url 'accounts:logout' %}">ロウグアウトはこちら</a>
気づきませんでした修正します！

2022-09-06 10:03 UTC, okapiinosuke commented
LGTM！
2次レビューをお待ちください。

2022-09-07 04:33 UTC, Akinori13 requested changes
とても良いと思います！！少しだけコメントしました！！

2022-09-07 04:33 UTC, Akinori13 commented on accounts/urls.py
> +    ),
ここはstrでも全然問題なかったですが、このまま進めてokです

2022-09-07 04:33 UTC, Akinori13 commented on accounts/models.py
> +    slug = models.SlugField(max_length=150, blank=False, unique=True)
slug単体だと良く分からないので、slugfied_usernameとかの方が良いかもしれないです
プロパティ使ってもよかったですね

2022-09-07 04:33 UTC, Akinori13 commented on tweets/views.py
> +    def test_func(self):
[この記事](https://www.django-antipatterns.com/antipattern/checking-ownership-through-the-userpassestestmixin.html)ではより良くする方法が記載されていますが、`get_object()`を使用してもいいと思います

2022-09-07 04:33 UTC, Akinori13 commented on tweets/tests.py
> +        self.client.post(reverse("accounts:signup"), user)
ツイート登録機能とSignup機能を分離するように気をつけましょう。今回であればユーザー登録（User.objects.create）して、client.login()を使いましょう！！

2022-09-07 07:09 UTC, pg-endokenta commented on accounts/models.py
> +    slug = models.SlugField(max_length=150, blank=False, unique=True)
slugified_usernameに変更しました

2022-09-07 07:10 UTC, pg-endokenta commented on accounts/models.py
> +    slug = models.SlugField(max_length=150, blank=False, unique=True)
プロパティを使ってもよかったとはどういうことでしょうか？

2022-09-07 07:25 UTC, pg-endokenta commented on tweets/views.py
> +    def test_func(self):
get_querysetを使用する方式に変更しました

2022-09-07 07:57 UTC, pg-endokenta commented on tweets/tests.py
> +        self.client.post(reverse("accounts:signup"), user)
ツイート機能のテストにおいてSignup機能を使わないように変更しました

2022-09-08 10:32 UTC, Akinori13 commented
LGTM

2022-09-08 10:32 UTC, merged