Feature/like
shinonome-inc/backend-final-assignment-EndoKenta pull request #5
Opened 2022-09-15 09:03 UTC by pg-endokenta

いいね機能を実装しました
<img width="1200" alt="スクリーンショット 2022-09-15 17 43 24" src="https://user-images.githubusercontent.com/104420143/190362366-66eeec1b-dabb-46bd-ac4b-532b18c7003d.png">
<img width="1202" alt="スクリーンショット 2022-09-15 17 45 53" src="https://user-images.githubusercontent.com/104420143/190362377-dc4446d3-7067-42bc-83e2-0ee0e5062e1d.png">
<img width="1201" alt="スクリーンショット 2022-09-15 17 43 59" src="https://user-images.githubusercontent.com/104420143/190362395-95e89627-ca5a-42e6-9e97-63679f5693e7.png">
<img width="511" alt="スクリーンショット 2022-09-15 17 52 27" src="https://user-images.githubusercontent.com/104420143/190362431-a5c403bc-60c0-4544-a7a9-e442bd8c44ee.png">

2022-09-17 02:07 UTC, Snak21-FPB requested changes
コメントしました：
- [ ] accounts/urls.py 内のコメントアウトされたViewを（使われていないと考えられるため）削除してください
- [ ] 詳細画面のいいねボタン
- [ ] Likeモデルのユニーク制約

2022-09-17 02:07 UTC, Snak21-FPB commented on templates/tweets/detail.html
> +            <button class="btn btn-light">{{ object.like_set.count }}件のイイね</button>
このボタン（詳細画面のいいね）が機能していないようです

2022-09-17 02:07 UTC, Snak21-FPB commented on tweets/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
`Like` モデルは、`user` と `tweet` の組み合わせがユニークであることが求められます（１ユーザーはツイートにつき２回以上いいねすることはない）ので、制約を付けてください。

2022-09-17 04:10 UTC, pg-endokenta commented on templates/tweets/detail.html
> +            <button class="btn btn-light">{{ object.like_set.count }}件のイイね</button>
イイねボタンが機能するようにしました。

（最終課題の要項によるとツイートの詳細画面ではイイねの数だけ表示できれば良いのですが、レイアウトを整えるためにボタンにしてしまいました。）

2022-09-17 04:10 UTC, pg-endokenta commented on tweets/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
了解しました

2022-09-17 04:53 UTC, Snak21-FPB approved these changes
問題が解決したため、Approve して二次レビューに回します👍

2022-09-19 06:26 UTC, masaya09 commented on accounts/views.py
> +        context["tweets"] = (
UserProfileViewでn + 1問題が起きてるので、ここの修正お願いします

2022-09-19 08:33 UTC, pg-endokenta commented on templates/tweets/detail.html
> +                class="btn btn-light">{{ object.like_set.count }}件のイイね</button>
tweetに統一しました。

objectとtweetが混在していたことに理由はありません

2022-09-19 08:35 UTC, pg-endokenta commented on accounts/views.py
> +        context["tweets"] = (
修正しました
修正前↓
<img width="1440" alt="スクリーンショット 2022-09-19 17 20 55" src="https://user-images.githubusercontent.com/104420143/190979199-3b64e010-3fe3-4e37-9218-1b1d5976e35b.png">
修正後↓
<img width="1440" alt="スクリーンショット 2022-09-19 17 24 02" src="https://user-images.githubusercontent.com/104420143/190979212-85a23ac1-e107-4e6a-bc78-0c7184455ec1.png">

2022-09-19 09:01 UTC, masaya09 reviewed
LGTM

2022-09-19 09:01 UTC, merged